### Add Message
POST http://localhost:8080/message2
Content-Type: application/json

{
  "word": "메이플",
  "timestamp": "2020–08–28T09:20:26.187"
}
### Add Message
POST http://localhost:8080/message2
Content-Type: application/json

{
  "word": "피파",
  "timestamp": "2020–08–28T09:20:26.187"
}
### Add Message
POST http://localhost:8080/message2
Content-Type: application/json

{
  "word": "던파",
  "timestamp": "2020–08–28T09:20:26.187"
}
### Add Message
POST http://localhost:8080/message2
Content-Type: application/json

{
  "word": "김경한",
  "timestamp": "2020–08–28T09:20:26.187"
}
### Add Message
POST http://localhost:8080/message2
Content-Type: application/json

{
  "word": "김경한",
  "timestamp": "2020–08–28T09:20:26.187"
}


### Add Message
POST http://localhost:8080/message2
Content-Type: application/json

{
  "word": "피파",
  "timestamp": "2020–08–28T09:20:26.187"
}


### Add Message
POST http://localhost:8080/message2
Content-Type: application/json

{
  "word": "OpenAPI",
  "timestamp": "2020–08–28T09:20:26.187"
}

### Add Message
POST http://localhost:8080/message2
Content-Type: application/json

{
  "word": "OpenAPI",
  "timestamp": "2020–08–28T09:20:26.187"
}

### Add Message
POST http://localhost:8080/message2
Content-Type: application/json

{
  "word": "전세제도 철폐하라!!",
  "timestamp": "2020–08–28T09:20:26.187"
}

### Add Message
POST http://localhost:8080/message2
Content-Type: application/json

{
  "word": "전세제도 철폐하라!!",
  "timestamp": "2020–08–28T09:20:26.187"
}

### Add Message
POST http://localhost:8080/message2
Content-Type: application/json

{
  "word": "전세제도 철폐하라!!",
  "timestamp": "2020–08–28T09:20:26.187"
}

### Add Message
POST http://localhost:8080/message2
Content-Type: application/json

{
  "word": "전세제도 철폐하라!!",
  "timestamp": "2020–08–28T09:20:26.187"
}

### Add Message
POST http://localhost:8080/message2
Content-Type: application/json

{
  "word": "패스트쿼리",
  "timestamp": "2020–08–28T09:20:26.187"
}

### Add Message
POST http://localhost:8080/message2
Content-Type: application/json

{
  "word": "패스트쿼리",
  "timestamp": "2020–08–28T09:20:26.187"
}

### Add Message
POST http://localhost:8080/message2
Content-Type: application/json

{
  "word": "패스트쿼리",
  "timestamp": "2020–08–28T09:20:26.187"
}

### Add Message
POST http://localhost:8080/message2
Content-Type: application/json

{
  "word": "패스트쿼리",
  "timestamp": "2020–08–28T09:20:26.187"
}

### Add Message
POST http://localhost:8080/message2
Content-Type: application/json

{
  "word": "패스트쿼리",
  "timestamp": "2020–08–28T09:20:26.187"
}

### Add Message
POST http://localhost:8080/message2
Content-Type: application/json

{
  "word": "패스트쿼리",
  "timestamp": "2020–08–28T09:20:26.187"
}
